/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layout;

import Clases.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Beto Leyva
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    OperacionesArchivo operaciones;
    List<Producto> productos;

    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Archivo Directo");

        productos = new ArrayList<>();

        operaciones = new OperacionesArchivo();

        productos = operaciones.getProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        LblClaveProducto = new javax.swing.JLabel();
        LblNombreProducto = new javax.swing.JLabel();
        lblHechoEn = new javax.swing.JLabel();
        LblPrecioCombra = new javax.swing.JLabel();
        TxtfClaveProducto = new javax.swing.JTextField();
        TxtfNombreProducto = new javax.swing.JTextField();
        TxtfHechoEn = new javax.swing.JTextField();
        TxtfPrecioCompra = new javax.swing.JTextField();
        btnGuardad = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        LblPrecioVenta = new javax.swing.JLabel();
        TxtfPrecioVenta = new javax.swing.JTextField();
        TxtfDescripcion = new javax.swing.JTextField();
        LblDescripcion = new javax.swing.JLabel();
        LblCompañiaFabricacion = new javax.swing.JLabel();
        TxtfCompañiaFabricacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.lightGray);

        lblTitulo.setBackground(new java.awt.Color(0, 204, 204));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Productos la Regiomontana S,A DE C.V");
        lblTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        LblClaveProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblClaveProducto.setText("Clave del Producto:");

        LblNombreProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblNombreProducto.setText("Nombre del Producto:");

        lblHechoEn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHechoEn.setText("Hecho en:");

        LblPrecioCombra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblPrecioCombra.setText("Precio de Compra:");

        TxtfClaveProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtfClaveProductoActionPerformed(evt);
            }
        });

        btnGuardad.setText("Guardar");
        btnGuardad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardadActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        LblPrecioVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblPrecioVenta.setText("Precio de Venta:");

        LblDescripcion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblDescripcion.setText("Descripcion:");

        LblCompañiaFabricacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblCompañiaFabricacion.setText("Compañia de fabricacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblClaveProducto)
                                    .addComponent(LblNombreProducto)
                                    .addComponent(lblHechoEn)
                                    .addComponent(LblPrecioCombra)
                                    .addComponent(LblPrecioVenta)
                                    .addComponent(LblDescripcion))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtfClaveProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(TxtfNombreProducto)
                                    .addComponent(TxtfHechoEn)
                                    .addComponent(TxtfPrecioCompra)
                                    .addComponent(TxtfPrecioVenta)
                                    .addComponent(TxtfCompañiaFabricacion)
                                    .addComponent(TxtfDescripcion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblCompañiaFabricacion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGuardad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnModificar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFinalizar)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblClaveProducto)
                    .addComponent(TxtfClaveProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombreProducto)
                    .addComponent(TxtfNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDescripcion))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHechoEn)
                    .addComponent(TxtfHechoEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPrecioCombra)
                    .addComponent(TxtfPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtfPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPrecioVenta))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCompañiaFabricacion)
                    .addComponent(TxtfCompañiaFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardad)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnFinalizar))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    public boolean validar() {
        Object[] datos = {
        TxtfClaveProducto.getText(),
        TxtfNombreProducto.getText(),
        TxtfDescripcion.getText(),
        TxtfHechoEn.getText(),
        TxtfPrecioCompra.getText(),
        TxtfPrecioVenta.getText(),
        TxtfCompañiaFabricacion.getText()
        };
        boolean result = true;
        
        for (int i = 0; i <= datos.length - 1; i++) {
            if (datos[i].toString().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Algunos campos estan vacios");
                result = false;
                break;
            }
        }
        
        return result;
    }
    
    
    private void btnGuardadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardadActionPerformed
        Producto producto = null;
        if(!validar())return;
        
        try {
            producto = new Producto(
                    TxtfClaveProducto.getText(),
                    TxtfNombreProducto.getText(),
                    TxtfDescripcion.getText(),
                    TxtfHechoEn.getText(),
                    Double.parseDouble(TxtfPrecioCompra.getText()),
                    Double.parseDouble(TxtfPrecioVenta.getText()),
                    TxtfCompañiaFabricacion.getText());
        } catch (Exception e) {
            System.out.println(e);
            producto = null;
        }

        operaciones.CrearProducto(producto);
    }//GEN-LAST:event_btnGuardadActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        productos = operaciones.getProductos();

        for (Producto producto : productos) {
            if (producto.getClaveProducto().equals(TxtfClaveProducto.getText())) {

                operaciones.BorrarProductoByClave(TxtfClaveProducto.getText());
                System.out.println("Registro encontrado");
                return;
            }
        }

        System.out.println("Registro no encontrado");

        productos = operaciones.getProductos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TxtfClaveProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtfClaveProductoActionPerformed

    }//GEN-LAST:event_TxtfClaveProductoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(!validar())return;
        
        Producto producto = null;
        try {
            producto = new Producto(
                    TxtfClaveProducto.getText(),
                    TxtfNombreProducto.getText(),
                    TxtfDescripcion.getText(),
                    TxtfHechoEn.getText(),
                    Double.parseDouble(TxtfPrecioCompra.getText()),
                    Double.parseDouble(TxtfPrecioVenta.getText()),
                    TxtfCompañiaFabricacion.getText());
        } catch (Exception e) {
            System.out.println("Error desde la interfaz"+e);
            producto = null;
        }
        if(producto != null){
            operaciones.ActualizarProductoByClave(producto);
        }else{
            System.out.println("Producto no valido");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblClaveProducto;
    private javax.swing.JLabel LblCompañiaFabricacion;
    private javax.swing.JLabel LblDescripcion;
    private javax.swing.JLabel LblNombreProducto;
    private javax.swing.JLabel LblPrecioCombra;
    private javax.swing.JLabel LblPrecioVenta;
    private javax.swing.JTextField TxtfClaveProducto;
    private javax.swing.JTextField TxtfCompañiaFabricacion;
    private javax.swing.JTextField TxtfDescripcion;
    private javax.swing.JTextField TxtfHechoEn;
    private javax.swing.JTextField TxtfNombreProducto;
    private javax.swing.JTextField TxtfPrecioCompra;
    private javax.swing.JTextField TxtfPrecioVenta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnGuardad;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblHechoEn;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
